#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaControlMed
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDInventarioMedico")]
	public partial class InventarioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserttbCategoria(tbCategoria instance);
    partial void UpdatetbCategoria(tbCategoria instance);
    partial void DeletetbCategoria(tbCategoria instance);
    partial void InserttbProducto(tbProducto instance);
    partial void UpdatetbProducto(tbProducto instance);
    partial void DeletetbProducto(tbProducto instance);
    partial void InserttbProveedor(tbProveedor instance);
    partial void UpdatetbProveedor(tbProveedor instance);
    partial void DeletetbProveedor(tbProveedor instance);
    partial void InserttbPrecioCosto(tbPrecioCosto instance);
    partial void UpdatetbPrecioCosto(tbPrecioCosto instance);
    partial void DeletetbPrecioCosto(tbPrecioCosto instance);
    partial void InserttbSalida(tbSalida instance);
    partial void UpdatetbSalida(tbSalida instance);
    partial void DeletetbSalida(tbSalida instance);
    partial void InserttbPresentacion(tbPresentacion instance);
    partial void UpdatetbPresentacion(tbPresentacion instance);
    partial void DeletetbPresentacion(tbPresentacion instance);
    partial void InserttbEntrada(tbEntrada instance);
    partial void UpdatetbEntrada(tbEntrada instance);
    partial void DeletetbEntrada(tbEntrada instance);
    partial void InserttbProductoProveedor(tbProductoProveedor instance);
    partial void UpdatetbProductoProveedor(tbProductoProveedor instance);
    partial void DeletetbProductoProveedor(tbProductoProveedor instance);
    partial void InserttbProductoPresentacion(tbProductoPresentacion instance);
    partial void UpdatetbProductoPresentacion(tbProductoPresentacion instance);
    partial void DeletetbProductoPresentacion(tbProductoPresentacion instance);
    partial void InserttbPrecioVenta(tbPrecioVenta instance);
    partial void UpdatetbPrecioVenta(tbPrecioVenta instance);
    partial void DeletetbPrecioVenta(tbPrecioVenta instance);
    partial void InserttbVentaProducto(tbVentaProducto instance);
    partial void UpdatetbVentaProducto(tbVentaProducto instance);
    partial void DeletetbVentaProducto(tbVentaProducto instance);
    partial void InserttbVenta(tbVenta instance);
    partial void UpdatetbVenta(tbVenta instance);
    partial void DeletetbVenta(tbVenta instance);
    partial void InserttbCliente(tbCliente instance);
    partial void UpdatetbCliente(tbCliente instance);
    partial void DeletetbCliente(tbCliente instance);
    partial void InserttbCajero(tbCajero instance);
    partial void UpdatetbCajero(tbCajero instance);
    partial void DeletetbCajero(tbCajero instance);
    #endregion
		
		public InventarioDataContext() : 
				base(global::SistemaControlMed.Properties.Settings.Default.BDInventarioMedicoConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public InventarioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InventarioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InventarioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InventarioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbCategoria> tbCategoria
		{
			get
			{
				return this.GetTable<tbCategoria>();
			}
		}
		
		public System.Data.Linq.Table<tbProducto> tbProducto
		{
			get
			{
				return this.GetTable<tbProducto>();
			}
		}
		
		public System.Data.Linq.Table<tbProveedor> tbProveedor
		{
			get
			{
				return this.GetTable<tbProveedor>();
			}
		}
		
		public System.Data.Linq.Table<tbPrecioCosto> tbPrecioCosto
		{
			get
			{
				return this.GetTable<tbPrecioCosto>();
			}
		}
		
		public System.Data.Linq.Table<tbSalida> tbSalida
		{
			get
			{
				return this.GetTable<tbSalida>();
			}
		}
		
		public System.Data.Linq.Table<tbPresentacion> tbPresentacion
		{
			get
			{
				return this.GetTable<tbPresentacion>();
			}
		}
		
		public System.Data.Linq.Table<tbEntrada> tbEntrada
		{
			get
			{
				return this.GetTable<tbEntrada>();
			}
		}
		
		public System.Data.Linq.Table<tbProductoProveedor> tbProductoProveedor
		{
			get
			{
				return this.GetTable<tbProductoProveedor>();
			}
		}
		
		public System.Data.Linq.Table<tbProductoPresentacion> tbProductoPresentacion
		{
			get
			{
				return this.GetTable<tbProductoPresentacion>();
			}
		}
		
		public System.Data.Linq.Table<tbPrecioVenta> tbPrecioVenta
		{
			get
			{
				return this.GetTable<tbPrecioVenta>();
			}
		}
		
		public System.Data.Linq.Table<tbVentaProducto> tbVentaProducto
		{
			get
			{
				return this.GetTable<tbVentaProducto>();
			}
		}
		
		public System.Data.Linq.Table<tbVenta> tbVenta
		{
			get
			{
				return this.GetTable<tbVenta>();
			}
		}
		
		public System.Data.Linq.Table<tbCliente> tbCliente
		{
			get
			{
				return this.GetTable<tbCliente>();
			}
		}
		
		public System.Data.Linq.Table<tbCajero> tbCajero
		{
			get
			{
				return this.GetTable<tbCajero>();
			}
		}
		
		public System.Data.Linq.Table<productoExistencia> productoExistencia
		{
			get
			{
				return this.GetTable<productoExistencia>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.OBTENER_PRODUCTOS", IsComposable=true)]
		public IQueryable<OBTENER_PRODUCTOSResult> OBTENER_PRODUCTOS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string prodNom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pres)
		{
			return this.CreateMethodCallQuery<OBTENER_PRODUCTOSResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prodNom, pres);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCategoria")]
	public partial class tbCategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codCategoria;
		
		private string _categoria;
		
		private string _descripcion;
		
		private EntitySet<tbProducto> _tbProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodCategoriaChanging(int value);
    partial void OncodCategoriaChanged();
    partial void OncategoriaChanging(string value);
    partial void OncategoriaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public tbCategoria()
		{
			this._tbProducto = new EntitySet<tbProducto>(new Action<tbProducto>(this.attach_tbProducto), new Action<tbProducto>(this.detach_tbProducto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCategoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codCategoria
		{
			get
			{
				return this._codCategoria;
			}
			set
			{
				if ((this._codCategoria != value))
				{
					this.OncodCategoriaChanging(value);
					this.SendPropertyChanging();
					this._codCategoria = value;
					this.SendPropertyChanged("codCategoria");
					this.OncodCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				if ((this._categoria != value))
				{
					this.OncategoriaChanging(value);
					this.SendPropertyChanging();
					this._categoria = value;
					this.SendPropertyChanged("categoria");
					this.OncategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCategoria_tbProducto", Storage="_tbProducto", ThisKey="codCategoria", OtherKey="codCategoria")]
		public EntitySet<tbProducto> tbProducto
		{
			get
			{
				return this._tbProducto;
			}
			set
			{
				this._tbProducto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbProducto(tbProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbCategoria = this;
		}
		
		private void detach_tbProducto(tbProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbCategoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbProducto")]
	public partial class tbProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codProducto;
		
		private string _nombre;
		
		private string _descripcion;
		
		private int _codCategoria;
		
		private string _ubicacion;
		
		private bool _estado;
		
		private EntitySet<tbProductoProveedor> _tbProductoProveedor;
		
		private EntitySet<tbProductoPresentacion> _tbProductoPresentacion;
		
		private EntityRef<tbCategoria> _tbCategoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodProductoChanging(int value);
    partial void OncodProductoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OncodCategoriaChanging(int value);
    partial void OncodCategoriaChanged();
    partial void OnubicacionChanging(string value);
    partial void OnubicacionChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    #endregion
		
		public tbProducto()
		{
			this._tbProductoProveedor = new EntitySet<tbProductoProveedor>(new Action<tbProductoProveedor>(this.attach_tbProductoProveedor), new Action<tbProductoProveedor>(this.detach_tbProductoProveedor));
			this._tbProductoPresentacion = new EntitySet<tbProductoPresentacion>(new Action<tbProductoPresentacion>(this.attach_tbProductoPresentacion), new Action<tbProductoPresentacion>(this.detach_tbProductoPresentacion));
			this._tbCategoria = default(EntityRef<tbCategoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this.OncodProductoChanging(value);
					this.SendPropertyChanging();
					this._codProducto = value;
					this.SendPropertyChanged("codProducto");
					this.OncodProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCategoria", DbType="Int NOT NULL")]
		public int codCategoria
		{
			get
			{
				return this._codCategoria;
			}
			set
			{
				if ((this._codCategoria != value))
				{
					if (this._tbCategoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodCategoriaChanging(value);
					this.SendPropertyChanging();
					this._codCategoria = value;
					this.SendPropertyChanged("codCategoria");
					this.OncodCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion", DbType="VarChar(5)")]
		public string ubicacion
		{
			get
			{
				return this._ubicacion;
			}
			set
			{
				if ((this._ubicacion != value))
				{
					this.OnubicacionChanging(value);
					this.SendPropertyChanging();
					this._ubicacion = value;
					this.SendPropertyChanged("ubicacion");
					this.OnubicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProducto_tbProductoProveedor", Storage="_tbProductoProveedor", ThisKey="codProducto", OtherKey="codProducto")]
		public EntitySet<tbProductoProveedor> tbProductoProveedor
		{
			get
			{
				return this._tbProductoProveedor;
			}
			set
			{
				this._tbProductoProveedor.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProducto_tbProductoPresentacion", Storage="_tbProductoPresentacion", ThisKey="codProducto", OtherKey="codProducto")]
		public EntitySet<tbProductoPresentacion> tbProductoPresentacion
		{
			get
			{
				return this._tbProductoPresentacion;
			}
			set
			{
				this._tbProductoPresentacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCategoria_tbProducto", Storage="_tbCategoria", ThisKey="codCategoria", OtherKey="codCategoria", IsForeignKey=true)]
		public tbCategoria tbCategoria
		{
			get
			{
				return this._tbCategoria.Entity;
			}
			set
			{
				tbCategoria previousValue = this._tbCategoria.Entity;
				if (((previousValue != value) 
							|| (this._tbCategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbCategoria.Entity = null;
						previousValue.tbProducto.Remove(this);
					}
					this._tbCategoria.Entity = value;
					if ((value != null))
					{
						value.tbProducto.Add(this);
						this._codCategoria = value.codCategoria;
					}
					else
					{
						this._codCategoria = default(int);
					}
					this.SendPropertyChanged("tbCategoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbProductoProveedor(tbProductoProveedor entity)
		{
			this.SendPropertyChanging();
			entity.tbProducto = this;
		}
		
		private void detach_tbProductoProveedor(tbProductoProveedor entity)
		{
			this.SendPropertyChanging();
			entity.tbProducto = null;
		}
		
		private void attach_tbProductoPresentacion(tbProductoPresentacion entity)
		{
			this.SendPropertyChanging();
			entity.tbProducto = this;
		}
		
		private void detach_tbProductoPresentacion(tbProductoPresentacion entity)
		{
			this.SendPropertyChanging();
			entity.tbProducto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbProveedor")]
	public partial class tbProveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codProveedor;
		
		private string _proveedor;
		
		private string _contacto;
		
		private string _direccion;
		
		private string _telefono;
		
		private string _codigoPostal;
		
		private string _fax;
		
		private string _nit;
		
		private string _estadoFiscal;
		
		private string _cuentaBancaria;
		
		private EntitySet<tbProductoProveedor> _tbProductoProveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodProveedorChanging(int value);
    partial void OncodProveedorChanged();
    partial void OnproveedorChanging(string value);
    partial void OnproveedorChanged();
    partial void OncontactoChanging(string value);
    partial void OncontactoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OncodigoPostalChanging(string value);
    partial void OncodigoPostalChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnnitChanging(string value);
    partial void OnnitChanged();
    partial void OnestadoFiscalChanging(string value);
    partial void OnestadoFiscalChanged();
    partial void OncuentaBancariaChanging(string value);
    partial void OncuentaBancariaChanged();
    #endregion
		
		public tbProveedor()
		{
			this._tbProductoProveedor = new EntitySet<tbProductoProveedor>(new Action<tbProductoProveedor>(this.attach_tbProductoProveedor), new Action<tbProductoProveedor>(this.detach_tbProductoProveedor));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProveedor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codProveedor
		{
			get
			{
				return this._codProveedor;
			}
			set
			{
				if ((this._codProveedor != value))
				{
					this.OncodProveedorChanging(value);
					this.SendPropertyChanging();
					this._codProveedor = value;
					this.SendPropertyChanged("codProveedor");
					this.OncodProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proveedor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string proveedor
		{
			get
			{
				return this._proveedor;
			}
			set
			{
				if ((this._proveedor != value))
				{
					this.OnproveedorChanging(value);
					this.SendPropertyChanging();
					this._proveedor = value;
					this.SendPropertyChanged("proveedor");
					this.OnproveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contacto", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string contacto
		{
			get
			{
				return this._contacto;
			}
			set
			{
				if ((this._contacto != value))
				{
					this.OncontactoChanging(value);
					this.SendPropertyChanging();
					this._contacto = value;
					this.SendPropertyChanged("contacto");
					this.OncontactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(20)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoPostal", DbType="VarChar(10)")]
		public string codigoPostal
		{
			get
			{
				return this._codigoPostal;
			}
			set
			{
				if ((this._codigoPostal != value))
				{
					this.OncodigoPostalChanging(value);
					this.SendPropertyChanging();
					this._codigoPostal = value;
					this.SendPropertyChanged("codigoPostal");
					this.OncodigoPostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(20)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit", DbType="VarChar(20)")]
		public string nit
		{
			get
			{
				return this._nit;
			}
			set
			{
				if ((this._nit != value))
				{
					this.OnnitChanging(value);
					this.SendPropertyChanging();
					this._nit = value;
					this.SendPropertyChanged("nit");
					this.OnnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadoFiscal", DbType="VarChar(20)")]
		public string estadoFiscal
		{
			get
			{
				return this._estadoFiscal;
			}
			set
			{
				if ((this._estadoFiscal != value))
				{
					this.OnestadoFiscalChanging(value);
					this.SendPropertyChanging();
					this._estadoFiscal = value;
					this.SendPropertyChanged("estadoFiscal");
					this.OnestadoFiscalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuentaBancaria", DbType="VarChar(20)")]
		public string cuentaBancaria
		{
			get
			{
				return this._cuentaBancaria;
			}
			set
			{
				if ((this._cuentaBancaria != value))
				{
					this.OncuentaBancariaChanging(value);
					this.SendPropertyChanging();
					this._cuentaBancaria = value;
					this.SendPropertyChanged("cuentaBancaria");
					this.OncuentaBancariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProveedor_tbProductoProveedor", Storage="_tbProductoProveedor", ThisKey="codProveedor", OtherKey="codProveedor")]
		public EntitySet<tbProductoProveedor> tbProductoProveedor
		{
			get
			{
				return this._tbProductoProveedor;
			}
			set
			{
				this._tbProductoProveedor.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbProductoProveedor(tbProductoProveedor entity)
		{
			this.SendPropertyChanging();
			entity.tbProveedor = this;
		}
		
		private void detach_tbProductoProveedor(tbProductoProveedor entity)
		{
			this.SendPropertyChanging();
			entity.tbProveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPrecioCosto")]
	public partial class tbPrecioCosto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codPrecioCosto;
		
		private int _codProductoProveedor;
		
		private decimal _precio;
		
		private System.DateTime _fechaCambio;
		
		private int _estado;
		
		private EntityRef<tbProductoProveedor> _tbProductoProveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodPrecioCostoChanging(int value);
    partial void OncodPrecioCostoChanged();
    partial void OncodProductoProveedorChanging(int value);
    partial void OncodProductoProveedorChanged();
    partial void OnprecioChanging(decimal value);
    partial void OnprecioChanged();
    partial void OnfechaCambioChanging(System.DateTime value);
    partial void OnfechaCambioChanged();
    partial void OnestadoChanging(int value);
    partial void OnestadoChanged();
    #endregion
		
		public tbPrecioCosto()
		{
			this._tbProductoProveedor = default(EntityRef<tbProductoProveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPrecioCosto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codPrecioCosto
		{
			get
			{
				return this._codPrecioCosto;
			}
			set
			{
				if ((this._codPrecioCosto != value))
				{
					this.OncodPrecioCostoChanging(value);
					this.SendPropertyChanging();
					this._codPrecioCosto = value;
					this.SendPropertyChanged("codPrecioCosto");
					this.OncodPrecioCostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoProveedor", DbType="Int NOT NULL")]
		public int codProductoProveedor
		{
			get
			{
				return this._codProductoProveedor;
			}
			set
			{
				if ((this._codProductoProveedor != value))
				{
					if (this._tbProductoProveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodProductoProveedorChanging(value);
					this.SendPropertyChanging();
					this._codProductoProveedor = value;
					this.SendPropertyChanged("codProductoProveedor");
					this.OncodProductoProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="SmallMoney NOT NULL")]
		public decimal precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCambio", DbType="Date NOT NULL")]
		public System.DateTime fechaCambio
		{
			get
			{
				return this._fechaCambio;
			}
			set
			{
				if ((this._fechaCambio != value))
				{
					this.OnfechaCambioChanging(value);
					this.SendPropertyChanging();
					this._fechaCambio = value;
					this.SendPropertyChanged("fechaCambio");
					this.OnfechaCambioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Int NOT NULL")]
		public int estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProductoProveedor_tbPrecioCosto", Storage="_tbProductoProveedor", ThisKey="codProductoProveedor", OtherKey="codProductoProveedor", IsForeignKey=true)]
		public tbProductoProveedor tbProductoProveedor
		{
			get
			{
				return this._tbProductoProveedor.Entity;
			}
			set
			{
				tbProductoProveedor previousValue = this._tbProductoProveedor.Entity;
				if (((previousValue != value) 
							|| (this._tbProductoProveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbProductoProveedor.Entity = null;
						previousValue.tbPrecioCosto.Remove(this);
					}
					this._tbProductoProveedor.Entity = value;
					if ((value != null))
					{
						value.tbPrecioCosto.Add(this);
						this._codProductoProveedor = value.codProductoProveedor;
					}
					else
					{
						this._codProductoProveedor = default(int);
					}
					this.SendPropertyChanged("tbProductoProveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbSalida")]
	public partial class tbSalida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codSalida;
		
		private int _codProductoPresentacion;
		
		private int _cantidad;
		
		private System.DateTime _fechaSalida;
		
		private bool _estado;
		
		private System.DateTime _fechaVencimiento;
		
		private EntityRef<tbProductoPresentacion> _tbProductoPresentacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodSalidaChanging(int value);
    partial void OncodSalidaChanged();
    partial void OncodProductoPresentacionChanging(int value);
    partial void OncodProductoPresentacionChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void OnfechaSalidaChanging(System.DateTime value);
    partial void OnfechaSalidaChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    partial void OnfechaVencimientoChanging(System.DateTime value);
    partial void OnfechaVencimientoChanged();
    #endregion
		
		public tbSalida()
		{
			this._tbProductoPresentacion = default(EntityRef<tbProductoPresentacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codSalida", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codSalida
		{
			get
			{
				return this._codSalida;
			}
			set
			{
				if ((this._codSalida != value))
				{
					this.OncodSalidaChanging(value);
					this.SendPropertyChanging();
					this._codSalida = value;
					this.SendPropertyChanged("codSalida");
					this.OncodSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoPresentacion", DbType="Int NOT NULL")]
		public int codProductoPresentacion
		{
			get
			{
				return this._codProductoPresentacion;
			}
			set
			{
				if ((this._codProductoPresentacion != value))
				{
					if (this._tbProductoPresentacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodProductoPresentacionChanging(value);
					this.SendPropertyChanging();
					this._codProductoPresentacion = value;
					this.SendPropertyChanged("codProductoPresentacion");
					this.OncodProductoPresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaSalida", DbType="Date NOT NULL")]
		public System.DateTime fechaSalida
		{
			get
			{
				return this._fechaSalida;
			}
			set
			{
				if ((this._fechaSalida != value))
				{
					this.OnfechaSalidaChanging(value);
					this.SendPropertyChanging();
					this._fechaSalida = value;
					this.SendPropertyChanged("fechaSalida");
					this.OnfechaSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaVencimiento", DbType="Date NOT NULL")]
		public System.DateTime fechaVencimiento
		{
			get
			{
				return this._fechaVencimiento;
			}
			set
			{
				if ((this._fechaVencimiento != value))
				{
					this.OnfechaVencimientoChanging(value);
					this.SendPropertyChanging();
					this._fechaVencimiento = value;
					this.SendPropertyChanged("fechaVencimiento");
					this.OnfechaVencimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProductoPresentacion_tbSalida", Storage="_tbProductoPresentacion", ThisKey="codProductoPresentacion", OtherKey="codProductoPresentacion", IsForeignKey=true)]
		public tbProductoPresentacion tbProductoPresentacion
		{
			get
			{
				return this._tbProductoPresentacion.Entity;
			}
			set
			{
				tbProductoPresentacion previousValue = this._tbProductoPresentacion.Entity;
				if (((previousValue != value) 
							|| (this._tbProductoPresentacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbProductoPresentacion.Entity = null;
						previousValue.tbSalida.Remove(this);
					}
					this._tbProductoPresentacion.Entity = value;
					if ((value != null))
					{
						value.tbSalida.Add(this);
						this._codProductoPresentacion = value.codProductoPresentacion;
					}
					else
					{
						this._codProductoPresentacion = default(int);
					}
					this.SendPropertyChanged("tbProductoPresentacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPresentacion")]
	public partial class tbPresentacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codPresentacion;
		
		private string _presentacion;
		
		private string _descripcion;
		
		private EntitySet<tbEntrada> _tbEntrada;
		
		private EntitySet<tbProductoPresentacion> _tbProductoPresentacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodPresentacionChanging(int value);
    partial void OncodPresentacionChanged();
    partial void OnpresentacionChanging(string value);
    partial void OnpresentacionChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public tbPresentacion()
		{
			this._tbEntrada = new EntitySet<tbEntrada>(new Action<tbEntrada>(this.attach_tbEntrada), new Action<tbEntrada>(this.detach_tbEntrada));
			this._tbProductoPresentacion = new EntitySet<tbProductoPresentacion>(new Action<tbProductoPresentacion>(this.attach_tbProductoPresentacion), new Action<tbProductoPresentacion>(this.detach_tbProductoPresentacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPresentacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codPresentacion
		{
			get
			{
				return this._codPresentacion;
			}
			set
			{
				if ((this._codPresentacion != value))
				{
					this.OncodPresentacionChanging(value);
					this.SendPropertyChanging();
					this._codPresentacion = value;
					this.SendPropertyChanged("codPresentacion");
					this.OncodPresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_presentacion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string presentacion
		{
			get
			{
				return this._presentacion;
			}
			set
			{
				if ((this._presentacion != value))
				{
					this.OnpresentacionChanging(value);
					this.SendPropertyChanging();
					this._presentacion = value;
					this.SendPropertyChanged("presentacion");
					this.OnpresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPresentacion_tbEntrada", Storage="_tbEntrada", ThisKey="codPresentacion", OtherKey="codPresentacion")]
		public EntitySet<tbEntrada> tbEntrada
		{
			get
			{
				return this._tbEntrada;
			}
			set
			{
				this._tbEntrada.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPresentacion_tbProductoPresentacion", Storage="_tbProductoPresentacion", ThisKey="codPresentacion", OtherKey="codPresentacion")]
		public EntitySet<tbProductoPresentacion> tbProductoPresentacion
		{
			get
			{
				return this._tbProductoPresentacion;
			}
			set
			{
				this._tbProductoPresentacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbEntrada(tbEntrada entity)
		{
			this.SendPropertyChanging();
			entity.tbPresentacion = this;
		}
		
		private void detach_tbEntrada(tbEntrada entity)
		{
			this.SendPropertyChanging();
			entity.tbPresentacion = null;
		}
		
		private void attach_tbProductoPresentacion(tbProductoPresentacion entity)
		{
			this.SendPropertyChanging();
			entity.tbPresentacion = this;
		}
		
		private void detach_tbProductoPresentacion(tbProductoPresentacion entity)
		{
			this.SendPropertyChanging();
			entity.tbPresentacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbEntrada")]
	public partial class tbEntrada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codEntrada;
		
		private int _codProductoProveedor;
		
		private int _codPresentacion;
		
		private decimal _costoEntrada;
		
		private int _cantidad;
		
		private System.DateTime _fechaIngreso;
		
		private System.Nullable<System.DateTime> _fechaVencimiento;
		
		private EntityRef<tbPresentacion> _tbPresentacion;
		
		private EntityRef<tbProductoProveedor> _tbProductoProveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodEntradaChanging(int value);
    partial void OncodEntradaChanged();
    partial void OncodProductoProveedorChanging(int value);
    partial void OncodProductoProveedorChanged();
    partial void OncodPresentacionChanging(int value);
    partial void OncodPresentacionChanged();
    partial void OncostoEntradaChanging(decimal value);
    partial void OncostoEntradaChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void OnfechaIngresoChanging(System.DateTime value);
    partial void OnfechaIngresoChanged();
    partial void OnfechaVencimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaVencimientoChanged();
    #endregion
		
		public tbEntrada()
		{
			this._tbPresentacion = default(EntityRef<tbPresentacion>);
			this._tbProductoProveedor = default(EntityRef<tbProductoProveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEntrada", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codEntrada
		{
			get
			{
				return this._codEntrada;
			}
			set
			{
				if ((this._codEntrada != value))
				{
					this.OncodEntradaChanging(value);
					this.SendPropertyChanging();
					this._codEntrada = value;
					this.SendPropertyChanged("codEntrada");
					this.OncodEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoProveedor", DbType="Int NOT NULL")]
		public int codProductoProveedor
		{
			get
			{
				return this._codProductoProveedor;
			}
			set
			{
				if ((this._codProductoProveedor != value))
				{
					if (this._tbProductoProveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodProductoProveedorChanging(value);
					this.SendPropertyChanging();
					this._codProductoProveedor = value;
					this.SendPropertyChanged("codProductoProveedor");
					this.OncodProductoProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPresentacion", DbType="Int NOT NULL")]
		public int codPresentacion
		{
			get
			{
				return this._codPresentacion;
			}
			set
			{
				if ((this._codPresentacion != value))
				{
					if (this._tbPresentacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodPresentacionChanging(value);
					this.SendPropertyChanging();
					this._codPresentacion = value;
					this.SendPropertyChanged("codPresentacion");
					this.OncodPresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costoEntrada", DbType="SmallMoney NOT NULL")]
		public decimal costoEntrada
		{
			get
			{
				return this._costoEntrada;
			}
			set
			{
				if ((this._costoEntrada != value))
				{
					this.OncostoEntradaChanging(value);
					this.SendPropertyChanging();
					this._costoEntrada = value;
					this.SendPropertyChanged("costoEntrada");
					this.OncostoEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaIngreso", DbType="Date NOT NULL")]
		public System.DateTime fechaIngreso
		{
			get
			{
				return this._fechaIngreso;
			}
			set
			{
				if ((this._fechaIngreso != value))
				{
					this.OnfechaIngresoChanging(value);
					this.SendPropertyChanging();
					this._fechaIngreso = value;
					this.SendPropertyChanged("fechaIngreso");
					this.OnfechaIngresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaVencimiento", DbType="Date")]
		public System.Nullable<System.DateTime> fechaVencimiento
		{
			get
			{
				return this._fechaVencimiento;
			}
			set
			{
				if ((this._fechaVencimiento != value))
				{
					this.OnfechaVencimientoChanging(value);
					this.SendPropertyChanging();
					this._fechaVencimiento = value;
					this.SendPropertyChanged("fechaVencimiento");
					this.OnfechaVencimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPresentacion_tbEntrada", Storage="_tbPresentacion", ThisKey="codPresentacion", OtherKey="codPresentacion", IsForeignKey=true)]
		public tbPresentacion tbPresentacion
		{
			get
			{
				return this._tbPresentacion.Entity;
			}
			set
			{
				tbPresentacion previousValue = this._tbPresentacion.Entity;
				if (((previousValue != value) 
							|| (this._tbPresentacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbPresentacion.Entity = null;
						previousValue.tbEntrada.Remove(this);
					}
					this._tbPresentacion.Entity = value;
					if ((value != null))
					{
						value.tbEntrada.Add(this);
						this._codPresentacion = value.codPresentacion;
					}
					else
					{
						this._codPresentacion = default(int);
					}
					this.SendPropertyChanged("tbPresentacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProductoProveedor_tbEntrada", Storage="_tbProductoProveedor", ThisKey="codProductoProveedor", OtherKey="codProductoProveedor", IsForeignKey=true)]
		public tbProductoProveedor tbProductoProveedor
		{
			get
			{
				return this._tbProductoProveedor.Entity;
			}
			set
			{
				tbProductoProveedor previousValue = this._tbProductoProveedor.Entity;
				if (((previousValue != value) 
							|| (this._tbProductoProveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbProductoProveedor.Entity = null;
						previousValue.tbEntrada.Remove(this);
					}
					this._tbProductoProveedor.Entity = value;
					if ((value != null))
					{
						value.tbEntrada.Add(this);
						this._codProductoProveedor = value.codProductoProveedor;
					}
					else
					{
						this._codProductoProveedor = default(int);
					}
					this.SendPropertyChanged("tbProductoProveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbProductoProveedor")]
	public partial class tbProductoProveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codProductoProveedor;
		
		private int _codProveedor;
		
		private int _codProducto;
		
		private EntitySet<tbPrecioCosto> _tbPrecioCosto;
		
		private EntitySet<tbEntrada> _tbEntrada;
		
		private EntityRef<tbProducto> _tbProducto;
		
		private EntityRef<tbProveedor> _tbProveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodProductoProveedorChanging(int value);
    partial void OncodProductoProveedorChanged();
    partial void OncodProveedorChanging(int value);
    partial void OncodProveedorChanged();
    partial void OncodProductoChanging(int value);
    partial void OncodProductoChanged();
    #endregion
		
		public tbProductoProveedor()
		{
			this._tbPrecioCosto = new EntitySet<tbPrecioCosto>(new Action<tbPrecioCosto>(this.attach_tbPrecioCosto), new Action<tbPrecioCosto>(this.detach_tbPrecioCosto));
			this._tbEntrada = new EntitySet<tbEntrada>(new Action<tbEntrada>(this.attach_tbEntrada), new Action<tbEntrada>(this.detach_tbEntrada));
			this._tbProducto = default(EntityRef<tbProducto>);
			this._tbProveedor = default(EntityRef<tbProveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoProveedor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codProductoProveedor
		{
			get
			{
				return this._codProductoProveedor;
			}
			set
			{
				if ((this._codProductoProveedor != value))
				{
					this.OncodProductoProveedorChanging(value);
					this.SendPropertyChanging();
					this._codProductoProveedor = value;
					this.SendPropertyChanged("codProductoProveedor");
					this.OncodProductoProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProveedor", DbType="Int NOT NULL")]
		public int codProveedor
		{
			get
			{
				return this._codProveedor;
			}
			set
			{
				if ((this._codProveedor != value))
				{
					if (this._tbProveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodProveedorChanging(value);
					this.SendPropertyChanging();
					this._codProveedor = value;
					this.SendPropertyChanged("codProveedor");
					this.OncodProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL")]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					if (this._tbProducto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodProductoChanging(value);
					this.SendPropertyChanging();
					this._codProducto = value;
					this.SendPropertyChanged("codProducto");
					this.OncodProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProductoProveedor_tbPrecioCosto", Storage="_tbPrecioCosto", ThisKey="codProductoProveedor", OtherKey="codProductoProveedor")]
		public EntitySet<tbPrecioCosto> tbPrecioCosto
		{
			get
			{
				return this._tbPrecioCosto;
			}
			set
			{
				this._tbPrecioCosto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProductoProveedor_tbEntrada", Storage="_tbEntrada", ThisKey="codProductoProveedor", OtherKey="codProductoProveedor")]
		public EntitySet<tbEntrada> tbEntrada
		{
			get
			{
				return this._tbEntrada;
			}
			set
			{
				this._tbEntrada.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProducto_tbProductoProveedor", Storage="_tbProducto", ThisKey="codProducto", OtherKey="codProducto", IsForeignKey=true)]
		public tbProducto tbProducto
		{
			get
			{
				return this._tbProducto.Entity;
			}
			set
			{
				tbProducto previousValue = this._tbProducto.Entity;
				if (((previousValue != value) 
							|| (this._tbProducto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbProducto.Entity = null;
						previousValue.tbProductoProveedor.Remove(this);
					}
					this._tbProducto.Entity = value;
					if ((value != null))
					{
						value.tbProductoProveedor.Add(this);
						this._codProducto = value.codProducto;
					}
					else
					{
						this._codProducto = default(int);
					}
					this.SendPropertyChanged("tbProducto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProveedor_tbProductoProveedor", Storage="_tbProveedor", ThisKey="codProveedor", OtherKey="codProveedor", IsForeignKey=true)]
		public tbProveedor tbProveedor
		{
			get
			{
				return this._tbProveedor.Entity;
			}
			set
			{
				tbProveedor previousValue = this._tbProveedor.Entity;
				if (((previousValue != value) 
							|| (this._tbProveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbProveedor.Entity = null;
						previousValue.tbProductoProveedor.Remove(this);
					}
					this._tbProveedor.Entity = value;
					if ((value != null))
					{
						value.tbProductoProveedor.Add(this);
						this._codProveedor = value.codProveedor;
					}
					else
					{
						this._codProveedor = default(int);
					}
					this.SendPropertyChanged("tbProveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbPrecioCosto(tbPrecioCosto entity)
		{
			this.SendPropertyChanging();
			entity.tbProductoProveedor = this;
		}
		
		private void detach_tbPrecioCosto(tbPrecioCosto entity)
		{
			this.SendPropertyChanging();
			entity.tbProductoProveedor = null;
		}
		
		private void attach_tbEntrada(tbEntrada entity)
		{
			this.SendPropertyChanging();
			entity.tbProductoProveedor = this;
		}
		
		private void detach_tbEntrada(tbEntrada entity)
		{
			this.SendPropertyChanging();
			entity.tbProductoProveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbProductoPresentacion")]
	public partial class tbProductoPresentacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codProductoPresentacion;
		
		private int _codProducto;
		
		private int _codPresentacion;
		
		private EntitySet<tbSalida> _tbSalida;
		
		private EntitySet<tbPrecioVenta> _tbPrecioVenta;
		
		private EntityRef<tbPresentacion> _tbPresentacion;
		
		private EntityRef<tbProducto> _tbProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodProductoPresentacionChanging(int value);
    partial void OncodProductoPresentacionChanged();
    partial void OncodProductoChanging(int value);
    partial void OncodProductoChanged();
    partial void OncodPresentacionChanging(int value);
    partial void OncodPresentacionChanged();
    #endregion
		
		public tbProductoPresentacion()
		{
			this._tbSalida = new EntitySet<tbSalida>(new Action<tbSalida>(this.attach_tbSalida), new Action<tbSalida>(this.detach_tbSalida));
			this._tbPrecioVenta = new EntitySet<tbPrecioVenta>(new Action<tbPrecioVenta>(this.attach_tbPrecioVenta), new Action<tbPrecioVenta>(this.detach_tbPrecioVenta));
			this._tbPresentacion = default(EntityRef<tbPresentacion>);
			this._tbProducto = default(EntityRef<tbProducto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoPresentacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codProductoPresentacion
		{
			get
			{
				return this._codProductoPresentacion;
			}
			set
			{
				if ((this._codProductoPresentacion != value))
				{
					this.OncodProductoPresentacionChanging(value);
					this.SendPropertyChanging();
					this._codProductoPresentacion = value;
					this.SendPropertyChanged("codProductoPresentacion");
					this.OncodProductoPresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL")]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					if (this._tbProducto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodProductoChanging(value);
					this.SendPropertyChanging();
					this._codProducto = value;
					this.SendPropertyChanged("codProducto");
					this.OncodProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPresentacion", DbType="Int NOT NULL")]
		public int codPresentacion
		{
			get
			{
				return this._codPresentacion;
			}
			set
			{
				if ((this._codPresentacion != value))
				{
					if (this._tbPresentacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodPresentacionChanging(value);
					this.SendPropertyChanging();
					this._codPresentacion = value;
					this.SendPropertyChanged("codPresentacion");
					this.OncodPresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProductoPresentacion_tbSalida", Storage="_tbSalida", ThisKey="codProductoPresentacion", OtherKey="codProductoPresentacion")]
		public EntitySet<tbSalida> tbSalida
		{
			get
			{
				return this._tbSalida;
			}
			set
			{
				this._tbSalida.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProductoPresentacion_tbPrecioVenta", Storage="_tbPrecioVenta", ThisKey="codProductoPresentacion", OtherKey="codProductoPresentacion")]
		public EntitySet<tbPrecioVenta> tbPrecioVenta
		{
			get
			{
				return this._tbPrecioVenta;
			}
			set
			{
				this._tbPrecioVenta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPresentacion_tbProductoPresentacion", Storage="_tbPresentacion", ThisKey="codPresentacion", OtherKey="codPresentacion", IsForeignKey=true)]
		public tbPresentacion tbPresentacion
		{
			get
			{
				return this._tbPresentacion.Entity;
			}
			set
			{
				tbPresentacion previousValue = this._tbPresentacion.Entity;
				if (((previousValue != value) 
							|| (this._tbPresentacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbPresentacion.Entity = null;
						previousValue.tbProductoPresentacion.Remove(this);
					}
					this._tbPresentacion.Entity = value;
					if ((value != null))
					{
						value.tbProductoPresentacion.Add(this);
						this._codPresentacion = value.codPresentacion;
					}
					else
					{
						this._codPresentacion = default(int);
					}
					this.SendPropertyChanged("tbPresentacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProducto_tbProductoPresentacion", Storage="_tbProducto", ThisKey="codProducto", OtherKey="codProducto", IsForeignKey=true)]
		public tbProducto tbProducto
		{
			get
			{
				return this._tbProducto.Entity;
			}
			set
			{
				tbProducto previousValue = this._tbProducto.Entity;
				if (((previousValue != value) 
							|| (this._tbProducto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbProducto.Entity = null;
						previousValue.tbProductoPresentacion.Remove(this);
					}
					this._tbProducto.Entity = value;
					if ((value != null))
					{
						value.tbProductoPresentacion.Add(this);
						this._codProducto = value.codProducto;
					}
					else
					{
						this._codProducto = default(int);
					}
					this.SendPropertyChanged("tbProducto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbSalida(tbSalida entity)
		{
			this.SendPropertyChanging();
			entity.tbProductoPresentacion = this;
		}
		
		private void detach_tbSalida(tbSalida entity)
		{
			this.SendPropertyChanging();
			entity.tbProductoPresentacion = null;
		}
		
		private void attach_tbPrecioVenta(tbPrecioVenta entity)
		{
			this.SendPropertyChanging();
			entity.tbProductoPresentacion = this;
		}
		
		private void detach_tbPrecioVenta(tbPrecioVenta entity)
		{
			this.SendPropertyChanging();
			entity.tbProductoPresentacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPrecioVenta")]
	public partial class tbPrecioVenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codPrecioVenta;
		
		private int _codProductoPresentacion;
		
		private decimal _precio;
		
		private bool _estado;
		
		private System.DateTime _fechaCambio;
		
		private EntitySet<tbVentaProducto> _tbVentaProducto;
		
		private EntityRef<tbProductoPresentacion> _tbProductoPresentacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodPrecioVentaChanging(int value);
    partial void OncodPrecioVentaChanged();
    partial void OncodProductoPresentacionChanging(int value);
    partial void OncodProductoPresentacionChanged();
    partial void OnprecioChanging(decimal value);
    partial void OnprecioChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    partial void OnfechaCambioChanging(System.DateTime value);
    partial void OnfechaCambioChanged();
    #endregion
		
		public tbPrecioVenta()
		{
			this._tbVentaProducto = new EntitySet<tbVentaProducto>(new Action<tbVentaProducto>(this.attach_tbVentaProducto), new Action<tbVentaProducto>(this.detach_tbVentaProducto));
			this._tbProductoPresentacion = default(EntityRef<tbProductoPresentacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPrecioVenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codPrecioVenta
		{
			get
			{
				return this._codPrecioVenta;
			}
			set
			{
				if ((this._codPrecioVenta != value))
				{
					this.OncodPrecioVentaChanging(value);
					this.SendPropertyChanging();
					this._codPrecioVenta = value;
					this.SendPropertyChanged("codPrecioVenta");
					this.OncodPrecioVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoPresentacion", DbType="Int NOT NULL")]
		public int codProductoPresentacion
		{
			get
			{
				return this._codProductoPresentacion;
			}
			set
			{
				if ((this._codProductoPresentacion != value))
				{
					if (this._tbProductoPresentacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodProductoPresentacionChanging(value);
					this.SendPropertyChanging();
					this._codProductoPresentacion = value;
					this.SendPropertyChanged("codProductoPresentacion");
					this.OncodProductoPresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="SmallMoney NOT NULL")]
		public decimal precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCambio", DbType="Date NOT NULL")]
		public System.DateTime fechaCambio
		{
			get
			{
				return this._fechaCambio;
			}
			set
			{
				if ((this._fechaCambio != value))
				{
					this.OnfechaCambioChanging(value);
					this.SendPropertyChanging();
					this._fechaCambio = value;
					this.SendPropertyChanged("fechaCambio");
					this.OnfechaCambioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPrecioVenta_tbVentaProducto", Storage="_tbVentaProducto", ThisKey="codPrecioVenta", OtherKey="codPrecioVenta")]
		public EntitySet<tbVentaProducto> tbVentaProducto
		{
			get
			{
				return this._tbVentaProducto;
			}
			set
			{
				this._tbVentaProducto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbProductoPresentacion_tbPrecioVenta", Storage="_tbProductoPresentacion", ThisKey="codProductoPresentacion", OtherKey="codProductoPresentacion", IsForeignKey=true)]
		public tbProductoPresentacion tbProductoPresentacion
		{
			get
			{
				return this._tbProductoPresentacion.Entity;
			}
			set
			{
				tbProductoPresentacion previousValue = this._tbProductoPresentacion.Entity;
				if (((previousValue != value) 
							|| (this._tbProductoPresentacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbProductoPresentacion.Entity = null;
						previousValue.tbPrecioVenta.Remove(this);
					}
					this._tbProductoPresentacion.Entity = value;
					if ((value != null))
					{
						value.tbPrecioVenta.Add(this);
						this._codProductoPresentacion = value.codProductoPresentacion;
					}
					else
					{
						this._codProductoPresentacion = default(int);
					}
					this.SendPropertyChanged("tbProductoPresentacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbVentaProducto(tbVentaProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbPrecioVenta = this;
		}
		
		private void detach_tbVentaProducto(tbVentaProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbPrecioVenta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbVentaProducto")]
	public partial class tbVentaProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codVentaProducto;
		
		private int _codPrecioVenta;
		
		private int _codVenta;
		
		private int _cantidad;
		
		private System.DateTime _fechaVencimiento;
		
		private EntityRef<tbPrecioVenta> _tbPrecioVenta;
		
		private EntityRef<tbVenta> _tbVenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodVentaProductoChanging(int value);
    partial void OncodVentaProductoChanged();
    partial void OncodPrecioVentaChanging(int value);
    partial void OncodPrecioVentaChanged();
    partial void OncodVentaChanging(int value);
    partial void OncodVentaChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void OnfechaVencimientoChanging(System.DateTime value);
    partial void OnfechaVencimientoChanged();
    #endregion
		
		public tbVentaProducto()
		{
			this._tbPrecioVenta = default(EntityRef<tbPrecioVenta>);
			this._tbVenta = default(EntityRef<tbVenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codVentaProducto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codVentaProducto
		{
			get
			{
				return this._codVentaProducto;
			}
			set
			{
				if ((this._codVentaProducto != value))
				{
					this.OncodVentaProductoChanging(value);
					this.SendPropertyChanging();
					this._codVentaProducto = value;
					this.SendPropertyChanged("codVentaProducto");
					this.OncodVentaProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPrecioVenta", DbType="Int NOT NULL")]
		public int codPrecioVenta
		{
			get
			{
				return this._codPrecioVenta;
			}
			set
			{
				if ((this._codPrecioVenta != value))
				{
					if (this._tbPrecioVenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodPrecioVentaChanging(value);
					this.SendPropertyChanging();
					this._codPrecioVenta = value;
					this.SendPropertyChanged("codPrecioVenta");
					this.OncodPrecioVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codVenta", DbType="Int NOT NULL")]
		public int codVenta
		{
			get
			{
				return this._codVenta;
			}
			set
			{
				if ((this._codVenta != value))
				{
					if (this._tbVenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodVentaChanging(value);
					this.SendPropertyChanging();
					this._codVenta = value;
					this.SendPropertyChanged("codVenta");
					this.OncodVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaVencimiento", DbType="Date NOT NULL")]
		public System.DateTime fechaVencimiento
		{
			get
			{
				return this._fechaVencimiento;
			}
			set
			{
				if ((this._fechaVencimiento != value))
				{
					this.OnfechaVencimientoChanging(value);
					this.SendPropertyChanging();
					this._fechaVencimiento = value;
					this.SendPropertyChanged("fechaVencimiento");
					this.OnfechaVencimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPrecioVenta_tbVentaProducto", Storage="_tbPrecioVenta", ThisKey="codPrecioVenta", OtherKey="codPrecioVenta", IsForeignKey=true)]
		public tbPrecioVenta tbPrecioVenta
		{
			get
			{
				return this._tbPrecioVenta.Entity;
			}
			set
			{
				tbPrecioVenta previousValue = this._tbPrecioVenta.Entity;
				if (((previousValue != value) 
							|| (this._tbPrecioVenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbPrecioVenta.Entity = null;
						previousValue.tbVentaProducto.Remove(this);
					}
					this._tbPrecioVenta.Entity = value;
					if ((value != null))
					{
						value.tbVentaProducto.Add(this);
						this._codPrecioVenta = value.codPrecioVenta;
					}
					else
					{
						this._codPrecioVenta = default(int);
					}
					this.SendPropertyChanged("tbPrecioVenta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbVenta_tbVentaProducto", Storage="_tbVenta", ThisKey="codVenta", OtherKey="codVenta", IsForeignKey=true)]
		public tbVenta tbVenta
		{
			get
			{
				return this._tbVenta.Entity;
			}
			set
			{
				tbVenta previousValue = this._tbVenta.Entity;
				if (((previousValue != value) 
							|| (this._tbVenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbVenta.Entity = null;
						previousValue.tbVentaProducto.Remove(this);
					}
					this._tbVenta.Entity = value;
					if ((value != null))
					{
						value.tbVentaProducto.Add(this);
						this._codVenta = value.codVenta;
					}
					else
					{
						this._codVenta = default(int);
					}
					this.SendPropertyChanged("tbVenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbVenta")]
	public partial class tbVenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codVenta;
		
		private int _numFactura;
		
		private System.Nullable<int> _codCliente;
		
		private int _codCajero;
		
		private System.DateTime _fechaVenta;
		
		private decimal _totalVenta;
		
		private bool _estado;
		
		private EntitySet<tbVentaProducto> _tbVentaProducto;
		
		private EntityRef<tbCliente> _tbCliente;
		
		private EntityRef<tbCajero> _tbCajero;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodVentaChanging(int value);
    partial void OncodVentaChanged();
    partial void OnnumFacturaChanging(int value);
    partial void OnnumFacturaChanged();
    partial void OncodClienteChanging(System.Nullable<int> value);
    partial void OncodClienteChanged();
    partial void OncodCajeroChanging(int value);
    partial void OncodCajeroChanged();
    partial void OnfechaVentaChanging(System.DateTime value);
    partial void OnfechaVentaChanged();
    partial void OntotalVentaChanging(decimal value);
    partial void OntotalVentaChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    #endregion
		
		public tbVenta()
		{
			this._tbVentaProducto = new EntitySet<tbVentaProducto>(new Action<tbVentaProducto>(this.attach_tbVentaProducto), new Action<tbVentaProducto>(this.detach_tbVentaProducto));
			this._tbCliente = default(EntityRef<tbCliente>);
			this._tbCajero = default(EntityRef<tbCajero>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codVenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codVenta
		{
			get
			{
				return this._codVenta;
			}
			set
			{
				if ((this._codVenta != value))
				{
					this.OncodVentaChanging(value);
					this.SendPropertyChanging();
					this._codVenta = value;
					this.SendPropertyChanged("codVenta");
					this.OncodVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numFactura", DbType="Int NOT NULL")]
		public int numFactura
		{
			get
			{
				return this._numFactura;
			}
			set
			{
				if ((this._numFactura != value))
				{
					this.OnnumFacturaChanging(value);
					this.SendPropertyChanging();
					this._numFactura = value;
					this.SendPropertyChanged("numFactura");
					this.OnnumFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCliente", DbType="Int")]
		public System.Nullable<int> codCliente
		{
			get
			{
				return this._codCliente;
			}
			set
			{
				if ((this._codCliente != value))
				{
					if (this._tbCliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodClienteChanging(value);
					this.SendPropertyChanging();
					this._codCliente = value;
					this.SendPropertyChanged("codCliente");
					this.OncodClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCajero", DbType="Int NOT NULL")]
		public int codCajero
		{
			get
			{
				return this._codCajero;
			}
			set
			{
				if ((this._codCajero != value))
				{
					if (this._tbCajero.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodCajeroChanging(value);
					this.SendPropertyChanging();
					this._codCajero = value;
					this.SendPropertyChanged("codCajero");
					this.OncodCajeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaVenta", DbType="DateTime NOT NULL")]
		public System.DateTime fechaVenta
		{
			get
			{
				return this._fechaVenta;
			}
			set
			{
				if ((this._fechaVenta != value))
				{
					this.OnfechaVentaChanging(value);
					this.SendPropertyChanging();
					this._fechaVenta = value;
					this.SendPropertyChanged("fechaVenta");
					this.OnfechaVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalVenta", DbType="SmallMoney NOT NULL")]
		public decimal totalVenta
		{
			get
			{
				return this._totalVenta;
			}
			set
			{
				if ((this._totalVenta != value))
				{
					this.OntotalVentaChanging(value);
					this.SendPropertyChanging();
					this._totalVenta = value;
					this.SendPropertyChanged("totalVenta");
					this.OntotalVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbVenta_tbVentaProducto", Storage="_tbVentaProducto", ThisKey="codVenta", OtherKey="codVenta")]
		public EntitySet<tbVentaProducto> tbVentaProducto
		{
			get
			{
				return this._tbVentaProducto;
			}
			set
			{
				this._tbVentaProducto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCliente_tbVenta", Storage="_tbCliente", ThisKey="codCliente", OtherKey="codCliente", IsForeignKey=true)]
		public tbCliente tbCliente
		{
			get
			{
				return this._tbCliente.Entity;
			}
			set
			{
				tbCliente previousValue = this._tbCliente.Entity;
				if (((previousValue != value) 
							|| (this._tbCliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbCliente.Entity = null;
						previousValue.tbVenta.Remove(this);
					}
					this._tbCliente.Entity = value;
					if ((value != null))
					{
						value.tbVenta.Add(this);
						this._codCliente = value.codCliente;
					}
					else
					{
						this._codCliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbCliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCajero_tbVenta", Storage="_tbCajero", ThisKey="codCajero", OtherKey="codCajero", IsForeignKey=true)]
		public tbCajero tbCajero
		{
			get
			{
				return this._tbCajero.Entity;
			}
			set
			{
				tbCajero previousValue = this._tbCajero.Entity;
				if (((previousValue != value) 
							|| (this._tbCajero.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbCajero.Entity = null;
						previousValue.tbVenta.Remove(this);
					}
					this._tbCajero.Entity = value;
					if ((value != null))
					{
						value.tbVenta.Add(this);
						this._codCajero = value.codCajero;
					}
					else
					{
						this._codCajero = default(int);
					}
					this.SendPropertyChanged("tbCajero");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbVentaProducto(tbVentaProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbVenta = this;
		}
		
		private void detach_tbVentaProducto(tbVentaProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbVenta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCliente")]
	public partial class tbCliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codCliente;
		
		private string _nombres;
		
		private string _apellidos;
		
		private string _nit;
		
		private string _telefono;
		
		private string _direccion;
		
		private EntitySet<tbVenta> _tbVenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodClienteChanging(int value);
    partial void OncodClienteChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OnnitChanging(string value);
    partial void OnnitChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    #endregion
		
		public tbCliente()
		{
			this._tbVenta = new EntitySet<tbVenta>(new Action<tbVenta>(this.attach_tbVenta), new Action<tbVenta>(this.detach_tbVenta));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codCliente
		{
			get
			{
				return this._codCliente;
			}
			set
			{
				if ((this._codCliente != value))
				{
					this.OncodClienteChanging(value);
					this.SendPropertyChanging();
					this._codCliente = value;
					this.SendPropertyChanged("codCliente");
					this.OncodClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit", DbType="VarChar(10)")]
		public string nit
		{
			get
			{
				return this._nit;
			}
			set
			{
				if ((this._nit != value))
				{
					this.OnnitChanging(value);
					this.SendPropertyChanging();
					this._nit = value;
					this.SendPropertyChanged("nit");
					this.OnnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(15)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(20)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCliente_tbVenta", Storage="_tbVenta", ThisKey="codCliente", OtherKey="codCliente")]
		public EntitySet<tbVenta> tbVenta
		{
			get
			{
				return this._tbVenta;
			}
			set
			{
				this._tbVenta.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbVenta(tbVenta entity)
		{
			this.SendPropertyChanging();
			entity.tbCliente = this;
		}
		
		private void detach_tbVenta(tbVenta entity)
		{
			this.SendPropertyChanging();
			entity.tbCliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCajero")]
	public partial class tbCajero : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codCajero;
		
		private string _nombres;
		
		private string _apellidos;
		
		private System.Nullable<System.DateTime> _fechaNacimiento;
		
		private string _telefono;
		
		private EntitySet<tbVenta> _tbVenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodCajeroChanging(int value);
    partial void OncodCajeroChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OnfechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaNacimientoChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    #endregion
		
		public tbCajero()
		{
			this._tbVenta = new EntitySet<tbVenta>(new Action<tbVenta>(this.attach_tbVenta), new Action<tbVenta>(this.detach_tbVenta));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCajero", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codCajero
		{
			get
			{
				return this._codCajero;
			}
			set
			{
				if ((this._codCajero != value))
				{
					this.OncodCajeroChanging(value);
					this.SendPropertyChanging();
					this._codCajero = value;
					this.SendPropertyChanged("codCajero");
					this.OncodCajeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this.OnfechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._fechaNacimiento = value;
					this.SendPropertyChanged("fechaNacimiento");
					this.OnfechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(15)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCajero_tbVenta", Storage="_tbVenta", ThisKey="codCajero", OtherKey="codCajero")]
		public EntitySet<tbVenta> tbVenta
		{
			get
			{
				return this._tbVenta;
			}
			set
			{
				this._tbVenta.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbVenta(tbVenta entity)
		{
			this.SendPropertyChanging();
			entity.tbCajero = this;
		}
		
		private void detach_tbVenta(tbVenta entity)
		{
			this.SendPropertyChanging();
			entity.tbCajero = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.productoExistencia")]
	public partial class productoExistencia
	{
		
		private string _Producto;
		
		private string _Presentacion;
		
		private System.Nullable<int> _Cantidad;
		
		public productoExistencia()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this._Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Presentacion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Presentacion
		{
			get
			{
				return this._Presentacion;
			}
			set
			{
				if ((this._Presentacion != value))
				{
					this._Presentacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	public partial class OBTENER_PRODUCTOSResult
	{
		
		private string _nombre;
		
		private string _presentacion;
		
		private string _categoria;
		
		private string _ubicacion;
		
		private int _cantidad;
		
		private System.DateTime _fechaIngreso;
		
		private System.Nullable<System.DateTime> _fechaVencimiento;
		
		public OBTENER_PRODUCTOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_presentacion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string presentacion
		{
			get
			{
				return this._presentacion;
			}
			set
			{
				if ((this._presentacion != value))
				{
					this._presentacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				if ((this._categoria != value))
				{
					this._categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion", DbType="VarChar(5)")]
		public string ubicacion
		{
			get
			{
				return this._ubicacion;
			}
			set
			{
				if ((this._ubicacion != value))
				{
					this._ubicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this._cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaIngreso", DbType="Date NOT NULL")]
		public System.DateTime fechaIngreso
		{
			get
			{
				return this._fechaIngreso;
			}
			set
			{
				if ((this._fechaIngreso != value))
				{
					this._fechaIngreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaVencimiento", DbType="Date")]
		public System.Nullable<System.DateTime> fechaVencimiento
		{
			get
			{
				return this._fechaVencimiento;
			}
			set
			{
				if ((this._fechaVencimiento != value))
				{
					this._fechaVencimiento = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
